sudo: required
dist: bionic
language: cpp

compiler:
    - clang
    - gcc

os:
    - linux
    - osx

env:
  - BUILD_MODE=release
  - BUILD_MODE=debug

install:
    - if [ "${TRAVIS_OS_NAME}" = "linux" -a "${CXX}" = "clang++" ]; then export MKSPEC=linux-clang; fi
    - if [ "${TRAVIS_OS_NAME}" = "linux" -a "${CXX}" = "g++" ]; then export MKSPEC=linux-g++; fi

    - if [ "${TRAVIS_OS_NAME}" = "osx" -a "${CXX}" = "clang++" ]; then export MKSPEC=macx-clang; fi
    - if [ "${TRAVIS_OS_NAME}" = "osx" -a "${CXX}" = "g++" ]; then export MKSPEC=macx-g++; fi

    - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sudo add-apt-repository ppa:beineri/opt-qt-5.14.1-bionic -y && sudo apt-get -y update -qq && sudo apt-get -y install qt514base qt514multimedia qt514declarative libgl-dev qt514svg &&  source /opt/qt*/bin/qt*-env.sh; fi

    - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew update; fi
    - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew install qt5; fi
    - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then export PATH=$(brew --prefix)/opt/qt5/bin:$PATH; fi

script:
    - echo "Building for ${MKSPEC} in ${BUILD_MODE} mode..."
    - mkdir build
    - cd build
    - qmake --version
    - qmake ../qtbooth.pro -spec ${MKSPEC} CONFIG+=${BUILD_MODE}
    - make
    - ls -lRa .
    - file qtbooth
