sudo: required
dist: disco
language: cpp

compiler:
    - clang
    - gcc

os:
    - linux
    - osx

env:
  - BUILD_MODE=release
  - BUILD_MODE=debug

install:
    - if [ "${TRAVIS_OS_NAME}" = "linux" -a "${CXX}" = "clang++" ]; then export MKSPEC=linux-clang; fi
    - if [ "${TRAVIS_OS_NAME}" = "linux" -a "${CXX}" = "g++" ]; then export MKSPEC=linux-g++; fi

    - if [ "${TRAVIS_OS_NAME}" = "osx" -a "${CXX}" = "clang++" ]; then export MKSPEC=macx-clang; fi
    - if [ "${TRAVIS_OS_NAME}" = "osx" -a "${CXX}" = "g++" ]; then export MKSPEC=macx-g++; fi

    - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa && sudo apt-get -y update -qq && sudo apt-get -y install qt5-default qml-module-qtmultimedia qtmultimedia5-dev qtdeclarative5-dev && export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake; fi

    - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew update; fi
    - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew install qt5; fi
    - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then export PATH=$(brew --prefix)/opt/qt5/bin:$PATH; fi

script:
    - echo "Building for ${MKSPEC} in ${BUILD_MODE} mode..."
    - mkdir build
    - cd build
    - qmake ../qtbooth.pro -qt=qt5 -spec ${MKSPEC} CONFIG+=${BUILD_MODE}
    - make
    - ls -lRa .
    - file qtbooth
